# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef32e1c44676887816b2d70b7fd8c2591a262b49b9a1f34056f127c8a87cfa8d24a139ffa17ef91f9a0d693f8bed600ff887c3e1da2ec725a0c6399e5dc37e4a

test:
  secret_key_base: 34729c9ef947af0ee7f64682b88f3fe16f5d379f78b372f9856022940c816b2d0717ddfd5b04374cdc8625eaaeda1a3600bc8148c29914d14b53310bde237d3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
