# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7bdbc59a89d7dd0476a3491f6036ba5f566adf9d1f21fc055ed1305eb882185bb0825d3f9643d9b8bbb47778b5e4491bb104a593875a2c63b594c5ed167a3b7

test:
  secret_key_base: 38a10582e0cdb15ea056d71b9a6014e40d0ec4947c745a05c2165fe36960ad8d4f979bc93dfbf46ffa1ac25923948e9927fddd1af033aad42560bc67d5a59817

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
